version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019" -A x64

build:
  project: build/FormatterInc.sln
  parallel: true
  verbosity: minimal

test: off

artifacts:
  - path: build\bin\$(configuration)\*.exe
    name: executables
  - path: build\lib\$(configuration)\*.lib
    name: libraries
