version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019" -A x64

build:
  project: build/ALL_BUILD.vcxproj 
  parallel: true
  verbosity: minimal

after_build:
  - cd build
  # Создаем MSI установщик
  - cpack -G WIX -C Release

artifacts:
  - path: build/*.msi
    name: installer
